# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example
end

target 'OneSignalLiveActivity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalLiveActivity
end

target 'ExampleWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleWidgetExtension
  pod 'OneSignalXCFramework', '>= 5.0.2', '< 6.0.0'
end
