name: Run Checks
on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install CSharpier
        run: dotnet tool install -g csharpier

      - name: Check formatting
        run: csharpier check .
